# Generated by Django 5.1.4 on 2024-12-08 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=255),
        ),
        migrations.AddField(
            model_name='member',
            name='fullname',
            field=models.CharField(default='John Doe', max_length=255),
        ),
        migrations.AddField(
            model_name='member',
            name='username',
            field=models.CharField(default='default_username', max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='password',
            field=models.CharField(default='default_password', max_length=128),
        ),
    ]
